name: "release"
on:
  push:
    branches:
      - refs/tags/*
jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: "install dfx"
      run: |
       wget https://sdk.dfinity.org/install.sh
       yes Y | DFX_VERSION=0.5.10 sh install.sh
       echo "::add-path::/home/runner/bin"
    - name: "dfx cache install"
      run: dfx cache install
    - name: "Create docs"
      run: ./bin/mo-doc
    - name: Upload docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/ # The folder the action should deploy.